;;; refactor-actions-smoke.el --- Real Kotlin action and rename -*- lexical-binding: t; -*-
(defvar jb-kotlin-navigation-smoke-no-run t)
(defconst jb-refactor-actions-fixture
  (expand-file-name "fixtures/refactor/Actions.kt" (file-name-directory load-file-name)))
(load (expand-file-name "navigation-smoke.el" (file-name-directory load-file-name)) nil t)
(ert-deftest jb-kotlin-live-refactoring-action-rename ()
  (let* ((project (expand-file-name "sources" jb-kotlin-smoke-root))
	 (default-directory (file-name-as-directory project))
	 (file (expand-file-name "src/WhenStatement.kt" project))
	 (text (with-temp-buffer (insert-file-contents jb-refactor-actions-fixture) (buffer-string))) workspace source)
    (with-temp-file file (insert text))
    (setq source (find-file-noselect file))
    (unwind-protect
	(progn
          (switch-to-buffer source)
          (jb-kotlin-smoke-mode)
          (setq jb-kotlin-projects (vector (list :type "json" :path (lsp--path-to-uri project))))
          (lsp-workspace-folders-add project)
          (lsp)
          (let ((deadline (+ (float-time) 80)))
            (while (not (and (setq workspace (car (lsp-workspaces)))
                             (eq 'initialized (lsp--workspace-status workspace))))
              (when (> (float-time) deadline) (error "Init timeout"))
              (accept-process-output nil 0.1)))
          (message "OPTIONS: %S" (jb-kotlin--initialization-options))
          (message "RENAME CAPABILITY: %S" (lsp-get (lsp--workspace-server-capabilities workspace) :renameProvider))
          (goto-char (point-min)) (search-forward "when") (backward-char)
          (let ((deadline (+ (float-time) 30)) actions renamed chosen)
            (while (and (not chosen) (< (float-time) deadline))
              (setq actions (lsp-code-actions-at-point))
              (message "Available actions: %S" (mapcar (lambda (a) (lsp-get a :title)) (append actions nil)))
              (setq chosen (cl-find-if (lambda (a) (string-match-p "Replace 'when' with 'if'" (lsp-get a :title))) actions))
              (unless chosen (accept-process-output nil 1)))
            (unless chosen (error "No Replace when with if action"))
            (let ((rename (symbol-function 'lsp-rename))
                  (idle-timer (symbol-function 'run-with-idle-timer)) idle-callback)
              (cl-letf (((symbol-function 'run-with-idle-timer)
			 (lambda (time repeat callback &rest args)
                           (if (and (equal time 0) (not repeat) (not (symbolp callback)) (null args))
                               (progn (setq idle-callback (cons callback args)) (timer-create))
                             (apply idle-timer time repeat callback args))))
			((symbol-function 'lsp-rename)
			 (lambda () (interactive)
			   (funcall rename "timestamp")
			   (setq renamed t))))
		(lsp-execute-code-action chosen)
		(let ((deadline (+ (float-time) 15)))
		  (while (and (not idle-callback) (< (float-time) deadline)) (accept-process-output nil 0.1)))
		;; Batch Emacs has no idle command loop.  Only dispatch after
		;; the original synchronous executeCommand has returned.
		(should idle-callback)
		(apply (car idle-callback) (cdr idle-callback))
		(should renamed)
		(should (string-match-p "val timestamp = System.currentTimeMillis()" (buffer-string)))
		(should (string-match-p "if (timestamp == 0L)" (buffer-string)))
		(should (string-match-p "if (timestamp == 1L)" (buffer-string)))
		(message "PASS: actual code action navigated, requested rename, and renamed declaration/references")))))
      (when workspace
	(when-let* ((log (lsp--workspace-ewoc workspace)))
          (with-current-buffer (ewoc-buffer log)
            (write-region (point-min) (point-max) (expand-file-name "refactoring-action-io.log" jb-kotlin-smoke-state) nil 'silent)))
	(lsp-workspace-shutdown workspace))
      (when (buffer-live-p source) (with-current-buffer source (set-buffer-modified-p nil))))))

(ert-run-tests-batch-and-exit 'jb-kotlin-live-refactoring-action-rename)
